### ISSUE TITLE
language of resources

### ISSUE THREAD

**Issue by csae8092** [KfNGOe/ferdinand-I-arche#4]
mit `hasLanguage` können 0:n Sprachen einer resource ausgezeichnet werden (wobei als range ein Concept aus https://vocabs.acdh.oeaw.ac.at/iso639_3/en/ gewählt werden muss)

sollten die TEI Daten es hergeben, wäre es denke ich schön, wenn die Sprachinformation in die ARCHE Metadaten übernommen werden könnte.

**Comment by rh1967** [comment]
nur top:collection und editions
